services:
  api:
    image: ${DOCKER_REGISTRY-}api
    container_name: api
    build:
      context: .
      dockerfile: Api/Dockerfile
    ports:
        - "5000:5000"
        - "5001:5001"
    depends_on:
        - garnet

  blazor:
    image: narforumuser:latest
    build:
      context: .
      dockerfile: NarForumUser/NarForumUser/Dockerfile
    ports:
      - "8080:8080"
      - "8081:8081"
    depends_on:
      - api

  forum.database:
    image: postgres:latest
    container_name: forum.database
    environment:
        - POSTGRES_USER=${POSTGRES_USER:-postgres}
        - POSTGRES_PASSWORD=${POSTGRES_USER:-postgres}
        - POSTGRES_MULTIPLE_DATABASES=forumidentitydb:postgres:postgres, forumdb:postgres:postgres
    volumes:
        - ./init-multiple-databases.sh:/docker-entrypoint-initdb.d/init-multiple-databases.sh
        - ./.containers/forumidentity-db:/var/lib/postgresql/data 
    ports:
        - 5432:5432

  garnet:
    image: 'ghcr.io/microsoft/garnet'
    ulimits:
      memlock: -1
    ports:
      - "6379:6379"
    volumes:
      - garnetdata:/data

volumes:
  garnetdata:

